<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="HYDVMERPCOE02"><DocLocation><![CDATA[\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\TestCases\ResultsSummary]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[ResultsSummary]]></DName>
<Res><![CDATA[Res39]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;OracleApplicationsHome&quot;  object was not found in the Object Repository.<BR>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\Config\Global.vbs<BR>Line (6): &quot;Set oOracleLogin = Browser(&quot;OracleApplicationsHome&quot;).Page(&quot;OracleApplicationsHome&quot;)&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:08]]></Time>
<TimeTick>1455269708</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="6" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\Config\Global.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;OracleEBS&quot;  object was not found in the Object Repository.<BR>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\Config\Global.vbs<BR>Line (7): &quot;Set oFSObj = Browser(&quot;OracleEBS&quot;).Page(&quot;OracleEBS&quot;)&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="7" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\Config\Global.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T5" iterID="1" >
<Action rID="T6">
<AName><![CDATA[rptWriteResultsSummary]]></AName>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Path not found<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (316): &quot;		Set objFolder = objFSO.GetFolder(strProjectResultPath &amp; &quot;\&quot; &amp; gFolderName &amp; &quot;\Testcases&quot;)&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="10" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFolder'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (317): &quot;		Set objFiles = objFolder.Files&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="11" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Path not found<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (321): &quot;		Set objFile = objFSO.CreateTextFile(SummaryChart, true, false)&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="12" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (323): &quot;		objFile.writeline &quot;&lt;table id='Logos'&gt; &lt;colgroup&gt; &lt;col style='width: 25%' /&gt; &lt;col style='width: 25%' /&gt; &lt;col style='width: 25%' /&gt; &lt;col style='width: 25%' /&gt; &lt;/colgroup&gt; &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="13" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (324): &quot;		objFile.writeline &quot;&lt;thead&gt;  &lt;tr class='content'&gt; &lt;th class ='Logos' colspan='2' &gt; &lt;img align ='left' src='.\Logos\Clientlogo.png ' height=60 width=140&gt;&lt;/img&gt; &lt;/th&gt;&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="14" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (325): &quot;		objFile.writeline &quot;&lt;th class = 'Logos' colspan='2' &gt; &lt;img align ='right' src='.\Logos\Companylogo.png ' height=60 width=140&gt;&lt;/img&gt; &lt;/th&gt; &lt;/tr&gt; &lt;/thead&gt; &lt;/table&gt; &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="15" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (326): &quot;		objFile.writeline &quot;&lt;html&gt; &lt;head&gt; &lt;script src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'&gt;&lt;/script&gt;&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="16" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (327): &quot;		objFile.writeline &quot;&lt;script src='/js/highcharts.js' type='text/javascript'&gt;&lt;/script&gt;&lt;script src='http://code.highcharts.com/highcharts.js'&gt;&lt;/script&gt;&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="17" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (328): &quot;		objFile.writeline &quot;&lt;script src='http://code.highcharts.com/highcharts-3d.js'&gt;&lt;/script&gt;&lt;script src='http://code.highcharts.com/modules/exporting.js'&gt;&lt;/script&gt;&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="18" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (329): &quot;		objFile.writeline &quot;&lt;meta charset='UTF-8'&gt; &lt;title&gt; Execution Summary Report&lt;/title&gt;&lt;style type='text/css'&gt;body {background-color: #FFFFFF; &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="19" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (330): &quot;		objFile.writeline &quot;font-family: Verdana, Geneva, sans-serif; text-align: center; } small { font-size: 0.7em; } table { box-shadow: 9px 9px 10px 4px #BDBDBD;&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="20" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (331): &quot;		objFile.writeline &quot;border: 0px solid #4D7C7B;border-collapse: collapse; border-spacing: 0px; width: 1000px; margin-left: auto; margin-right: auto; } &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="21" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (332): &quot;		objFile.writeline &quot;tr.heading { background-color: #041944;color: #FFFFFF; font-size: 0.7em; font-weight: bold; &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="22" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (333): &quot;		objFile.writeline &quot;background:-o-linear-gradient(bottom, #999999 5%, #000000 100%); &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="23" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (334): &quot;		objFile.writeline &quot;background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #999999), color-stop(1, #000000) );&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="24" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (335): &quot;		objFile.writeline &quot;background:-moz-linear-gradient( center top, #999999 5%, #000000 100% );&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="25" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (336): &quot;		objFile.writeline &quot;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#999999, endColorstr=#000000); &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="26" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (337): &quot;		objFile.writeline &quot;background:-o-linear-&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="27" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (338): &quot;		objFile.writeline &quot;gradient(top,#999999,000000);} tr.subheading { background-color: #6A90B6;color: #000000; font-weight: bold; font-size: 0.7em; &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="28" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (339): &quot;		objFile.writeline &quot;text-align:justify; } tr.section { background-color: #A4A4A4; color: #333300; cursor: pointer; font-weight: bold;font-size: 0.8em; &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="29" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (340): &quot;		objFile.writeline &quot;text-align: justify;&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="30" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (341): &quot;		objFile.writeline &quot;background:-o-linear-gradient(bottom, #56aaff 5%, #e5e5e5 100%); &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="31" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (342): &quot;		objFile.writeline &quot;background:-webkit-gradient( linear, left top, left bottom,color-stop(0.05, #56aaff), color-stop(1, #e5e5e5) );&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="32" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (343): &quot;		objFile.writeline &quot;background:-moz-linear-gradient( center top, #56aaff 5%, #e5e5e5 100% );&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:09]]></Time>
<TimeTick>1455269709</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="33" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (344): &quot;		objFile.writeline &quot;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#56aaff, endColorstr=#e5e5e5);&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:10]]></Time>
<TimeTick>1455269710</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="34" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (345): &quot;		objFile.writeline &quot;background:-o-linear-gradient(top,#56aaff,e5e5e5);} tr.subsection { cursor: pointer; } &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:10]]></Time>
<TimeTick>1455269710</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="35" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (346): &quot;		objFile.writeline &quot;tr.content { background-color: #FFFFFF; color:#000000; font-size: 0.7em; display: table-row; } &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:10]]></Time>
<TimeTick>1455269710</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="36" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (347): &quot;		objFile.writeline &quot;tr.content2 { background-color:#;E1E1E1border: 1px solid #4D7C7B;color: #000000; &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:10]]></Time>
<TimeTick>1455269710</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="37" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (348): &quot;		objFile.writeline &quot;font-size: 0.7em; display: table-row; } td, th { padding: 5px; border: 1px solid #4D7C7B; text-align: inherit/; } th.Logos {&quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:10]]></Time>
<TimeTick>1455269710</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="38" status="Failed" Source="\\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objFile'<BR>Function file: \\172.16.2.5\erp-coe\Oracle\OracleEBS\Accelerators\Automation\OracleEBSFramework\LibraryFiles\Reporting.vbs<BR>Line (349): &quot;		objFile.writeline &quot;padding: 5px; &quot;&quot;.]]></Details>
<Time><![CDATA[2/12/2016 - 15:05:10]]></Time>
<TimeTick>1455269710</TimeTick>